### ISSUE TITLE
Add the ability to get the cluster version

### ISSUE THREAD

**Issue by agrare** [abonas/kubeclient#399] opened 2019-02-28 22:06 UTC
The command-line tools allow a user to get the version of the cluster that they are connected to, e.g.:
```
oc version
openshift v3.11.43
kubernetes v1.11.0+d4cacc0
```

The endpoints appear to be `/version` and `/version/openshift`.

I'd like feedback on where best for this code to live, an instance of `Kubeclient::Client` already is scoped to e.g. `/api/v1` so it almost feels like a level above?  Really would like your feedback on this @cben

**Comment by cben** [comment] 2019-03-01 10:34
Closing as duplicate of #309.
I think this doesn't deserve a special method of its own (especially with the 2nd `/version/openshift` that's not appropriate to all clusters), but is perfect use case for adding #389.  You'd then do things like:
```
client.http_get('/version', as: :ros).goVersion
client.http_get('/version/openshift', as: :ros).gitVersion
```

**Closed** 2019-03-01 10:35 UTC
